### ISSUE TITLE
zpl_adt_node returned by zpl_json_parse() could have more useful parents

### ISSUE THREAD

**Issue by rheatley-pervasid** [zpl-c/zpl#100]
Hello,

I've been trying to pretty-print the JSON zpl_adt_node I am validating and realised the "parent" field is not set very helpfully.

Is it your intention this should be possible?
I think the usage of zpl_array_append makes it tricky as it is appending a stack allocated zpl_adt_node

I tested the following patch which seems to work. If you like I am happy to tidy it into a pull request or perhaps you can consider similar functionality in a future release.

Thank you,
Richard.

```
@@ -3920,6 +3920,15 @@ License:
          (x)[zpl_array_count(x)++] = (item);                                                                            \
      } while (0)

+     #define zpl_array_append_adt_node(x, item)                                                                             \
+     do {                                                                                                               \
+         zpl_array_append(x, item);                                                                                     \
+         if (item.type == ZPL_ADT_TYPE_OBJECT || item.type == ZPL_ADT_TYPE_ARRAY) {                                     \
+             for (zpl_isize i = 0; i < zpl_array_count(item.nodes); i++)                                                \
+                 item.nodes[i].parent = zpl_array_end(x);                                                               \
+         }                                                                                                              \
+     } while (0)
+
      #define zpl_array_append_at(x, item, ind)                                                                              \
      do {                                                                                                               \
          if (ind >= zpl_array_count(x)) { zpl_array_append(x, item); break; }                                               \
@@ -17555,7 +17564,7 @@ License:

              if (*err_code != ZPL_JSON_ERROR_NONE) { return NULL; }

-             zpl_array_append(obj->nodes, elem);
+             zpl_array_append_adt_node(obj->nodes, elem);

              p = zpl__json_trim(p, false);

@@ -17676,7 +17685,7 @@ License:
              p = zpl__json_parse_value(&node, p, a, err_code);
              if (err_code && *err_code != ZPL_JSON_ERROR_NONE) { return NULL; }

-             zpl_array_append(obj->nodes, node);
+             zpl_array_append_adt_node(obj->nodes, node);

              char *end_p = p; zpl_unused(end_p);
              p = zpl__json_trim(p, true);
```

**Comment by zpl-zak** [comment]
Hi, thank you for the bug report. This issue is now resolved in version [18.1.3](https://github.com/zpl-c/zpl/releases/tag/18.1.3)

**Comment by rheatley-pervasid** [comment]
@zpl-zak thank you for taking a look at the issue. I think sadly your change is not correct/safe.

When parsing the root (or any object) the node is initially created on the stack
https://github.com/zpl-c/zpl/blob/d80f6100b68eda3443e7164e506a78254627b864/code/source/parsers/json.c#L205

`node` is then passed into `zpl__json_parse_value` as a pointer to the stack variable so in later calls `obj` is still a pointer to the stack.
`node` isn't allocated from the allocator until the `zpl_array_append` call but all the child elements have the wrong parent at this point.
This is why I wrote the slightly obscure `zpl_array_append_adt_node` which retrospectively corrects the parent of all children. 

I _think_ my diagnosis is correct and it helps I seem to get incorrect results with your version (the parent nodes stop having names as they got zero-ed out by stack reuse)

**Comment by zpl-zak** [comment]
Thanks for the feedback; I'll be able to get back to it during the weekend. 👍🏻

**Comment by zpl-zak** [comment]
I had a look at it again, hopefully https://github.com/zpl-c/zpl/releases/tag/18.1.5 should resolve this issue now.
