### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [zpl-c/zpl#105]
Would you like to add more error handling for return values from functions like the following?
* [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex") ⇒ [zpl_mutex_init](https://github.com/zpl-c/zpl/blob/d22c646e3c2691e424513cf6316c734523b3cb45/code/source/threading/mutex.c#L6)
* [pthread_create](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html "Thread creation") ⇒ [zpl_thread_start_with_stack](https://github.com/zpl-c/zpl/blob/f73c713a5ebb22d306173d3179dae7b4d57354dd/code/source/threading/thread.c#L65)

**Comment by zpl-zak** [comment]
We could do that, indeed. I'll have a look into it! Sorry for the delay!

**Comment by elfring** [comment]
:thought_balloon: I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by zpl-zak** [comment]
Handled as of https://github.com/zpl-c/zpl/releases/tag/19.1.1
