### ISSUE TITLE
zpl_array_fill ZPL_ASSERT error

### ISSUE THREAD

**Issue by Bluelet** [zpl-c/zpl#107]
code/header/essentials/collections/array.h, line 193:
#define zpl_array_fill(x, begin, end, value)                                                                        \
do {                                                                                                               \
    ZPL_ASSERT((begin) >= 0 && (end) < zpl_array_count(x)); 

it should be:
    ZPL_ASSERT((begin) >= 0 && (end) <= zpl_array_count(x));

**Comment by zpl-zak** [comment]
Sorry for the delay, issue is fixed in https://github.com/zpl-c/zpl/releases/tag/19.0.1
