### ISSUE TITLE
ADT parsing of 'x' results in a ZPL_ADT_TYPE_INTEGER

### ISSUE THREAD

**Issue by rheatley-pervasid** [zpl-c/zpl#113]
Found when parsing a CSV. 
Not sure what the allowance of 'x' is trying to do here, https://github.com/zpl-c/zpl/blob/master/code/source/adt.c#L413

But it needs more than just that removing

**Comment by zpl-zak** [comment]
Hi, looks like an edge case where the method fails to exit early when it encounters "hex-looking" string. I will create a test case and have a fix ready soon.

**Comment by zpl-zak** [comment]
Should be fixed in https://github.com/zpl-c/zpl/releases/tag/19.3.1

**Comment by rheatley-pervasid** [comment]
Thank you!

**Comment by zpl-zak** [comment]
I am closing this one. Feel free to reopen it if anything comes up!
