### ISSUE TITLE
`zpl_file_open` and functions that call it do not error when passed a directory

### ISSUE THREAD

**Issue by restitux** [zpl-c/zpl#115]
`zpl_file_open` seems to run successfully when passed a directory path. This is very confusing, as this function doesn't seem well defined for a directory. Here is an example:

```c
zpl_file_error error;
zpl_file file = {0};
error = zpl_file_open(&file, "/path/to/directory");
printf("%d\n", error); // This prints ZPL_FILE_ERROR_NONE (0)
```
This becomes annoying when combined with other parts of the library.
Calling `zpl_file_read_contents` on a directory doesn't error. Instead, in my testing it returned `fc.size == 30` and `fc.data` as a 30 element array of null bytes. Once passed to the json parser, the user is left debugging errors that present themselves as mismatched `}]`s.

Thanks!

**Comment by zpl-zak** [comment]
Hi,

this is by design as a directory is also a file entry (which is then utilized for the dirlist API we have). I recommend calling `zpl_fs_get_type` on the given path first to check what file type the disk entry is, it returns `ZPL_DIR_TYPE_FOLDER` in such cases.

Cheers!

**Comment by restitux** [comment]
Ah I see, that makes sense. Do you think it would make sense to have `zpl_file_read_contents` check for `ZPL_DIR_TYPE_FOLDER` and set `fc.data` to `NULL` if so? I think that would help catch errors where you accidentally pass a directory to `zpl_file_read_contents`.

**Comment by zpl-zak** [comment]
Sure, that would make sense, I will add it tomorrow if that's fine. Thanks for the proposition!

**Comment by zpl-zak** [comment]
This is now resolved in https://github.com/zpl-c/zpl/releases/tag/19.4.1

**Comment by restitux** [comment]
Awesome, thanks for the quick fix!
