### ISSUE TITLE
Add thread pool

### ISSUE THREAD

**Issue by pbtrung** [zpl-c/zpl#16]
This would be helpful for my project and others.
Thanks.

**Comment by zaklaus** [comment]
I will look into that, having some sort of job system would be nice.

**Comment by zaklaus** [comment]
Added in 423eb61f2749d2af563137e2112815e6a443465b.

Let me know if that's good enough. You can find an example usage in test/jobs.c

**Comment by pbtrung** [comment]
Impressive. Very fast reply.
I will try this as long as I have some spare time.
Close this for now.
Thanks.
