### ISSUE TITLE
Cross-platform directory support

### ISSUE THREAD

**Issue by pbtrung** [zpl-c/zpl#17]
This should be a major feature.
Ref: https://github.com/tronkko/dirent
Thanks.

**Comment by pbtrung** [comment]
To be more specific, I would prefer APIs as in `dirent.h` rather than as in `stb.h`, which dumps every path into a big array.

**Comment by zaklaus** [comment]
I plan on expanding the current file module (zpl_file_*) and one of the major features I'd like to have is the ability to build up directory tree so user can easily traverse and manipulate files on the filesystem without having to deal with big arrays or strings like in zpl_path_dirlist for example.

**Comment by pbtrung** [comment]
This one is also an interesting implementation:
https://github.com/RandyGaul/tinyheaders/blob/master/tinyfiles.h
A callback is set on each found path.

**Comment by inlife** [comment]
oh i like the callback idea it seems much simpler to use

**Comment by zaklaus** [comment]
I've recently added new methods for handling directory lookup. Check out dirlist_api.c if it meets with the requirements. You can retrieve directory info both via standalone `zpl_dirinfo_init` method and also by refreshing the look up of the currently opened files (`zpl_file_dirinfo_refresh`). The API can tell you about the file type (right now, only types: file, folder) are supported.

Performing lookup on a folder scans that folder.
Performing lookup on a file scans the folder file is located in.

Scanned files are stored as entries within the dir_info structure. You can `step` into them to see what the subfolders contain by simply calling `zpl_dirinfo_step`.

The system makes use of `zpl_path_dirlist` internally. I've also added `zpl_fs_get_type` which checks for a file type (ie. is it a file or a folder, ...)

Let me know if there's anything I could add/modify.

**Comment by pbtrung** [comment]
Looks good. Will try as soon as I have some free time. Close this for now.
Thanks.
