### ISSUE TITLE
Add option to not clobber names that don't begin with `zpl_` or `ZPL_`

### ISSUE THREAD

**Issue by nilesr** [zpl-c/zpl#20]
Currently #including this library drops a bunch of stuff that you might otherwise be using into the global namespace, like defining `u8`, `i32`, `intptr`, and most importantly a macro called `cast`. It also does `#define NULL nullptr` if compiled for C++, which may break backwards compatability with existing C code when used inside C++.

Can these be defined conditionally?

**Comment by zaklaus** [comment]
I'll add the option to do that definitely, thanks.

**Comment by zaklaus** [comment]
Dealt with in 765104903851f1760b99fa60102141700610bf30 and e6723950603ab6b980f37ffb99b31cf463b3c3bd
