### ISSUE TITLE
Atomics aren't atomic

### ISSUE THREAD

**Issue by nilesr** [zpl-c/zpl#21]
The `zpl_atomic32`, `zpl_atomic64` and `zpl_atomic_ptr` are all declared as volatile, and are used unprotected by any guards. Atomics and volatile are [not the same thing](https://stackoverflow.com/questions/8819095/concurrency-atomic-and-volatile-in-c11-memory-model), and writes to volatile variables may still have the following problems:

- torn reads/writes
- on writes, work done to other variables on that thread may not be published, leading another thread to think it has acquired access to a critical region of code, but the data the code operates in does not have the first thread's changes. Clarification below

Quotes from the wikipedia page for [volatile variables](https://en.wikipedia.org/wiki/Volatile_(computer_programming):

- "in C and C++ it does not work in most threading scenarios, and that use is discouraged"
- "volatile variables are not threadsafe in the vast majority of current implementations"
- "the usage of volatile keyword as a portable synchronization mechanism is discouraged by many C/C++ groups"
- "neither the C specification (before C11) nor the C++ specification (before C++11) specifies a multi-threaded memory model, so volatile may not behave deterministically across OSes/compilers/CPUs"
- "According to the C++11 ISO Standard, the volatile keyword is only meant for use for hardware access; do not use it for inter-thread communication"

This is not helped by the fact that some people [perpetuate the myth that they're the same](https://stackoverflow.com/questions/25319825/how-to-use-atomic-variables-in-c) (referring to the M.M comment)

I don't know if there is a portable way of using atomics pre-C11, but volatile definitely isn't it.

To clarify my comment above, imagine there are two threads. The variable `a` is atomic, and `g` is global (not atomic). Both variables start out at 0. Thread 1 runs the following code

    g = 1;
    a = 1;

Thread 2 runs this code.

    if (a == 1) {
        assert(g == 1);
    }

If `a` is truly atomic, then the assertion in thread 2 must **NEVER** fail. However if `a` is only volatile, then the code may fail. In fact, `if (a == 1)` may not even run properly if Thread 2 gets a torn read on `a`, which can happen if `a` isn't atomic, only volatile. 

If `a` is being used to guard critical resources, this leads to subtle, hard-to-detect and hard-to-reproduce errors.

**Comment by zaklaus** [comment]
Thanks for this, I look into it more to fix this issue. I'm not sure what the solution for C99 might be yet, but I definitely know what not to do in the future, thanks.

**Comment by zaklaus** [comment]
This issue will be fixed for C11 and later. C99 will not support atomics unfortunately.
