### ISSUE TITLE
Argument/Option parsing w/positional arguments and flags only works with flags last

### ISSUE THREAD

**Issue by robozman** [zpl-c/zpl#22]
The argument and option parsing only seems to work when the flags are placed last
`./dug example.com 127.0.0.1 -d`
works while
`./dug -d example.com 127.0.0.1`                                                                                                        
does not.

Output from first case:

`hostname: example.com`
`dns_server: 127.0.0.1`
`debug_mode true`

Output from from second case:

`ERROR: Extra value for option ""`
`USAGE: ./dug [hostname] [dns_server]`
`OPTIONS:`
`    -n, --hostname: hostname to get DNS query for`
`    -s, --dns_server: dns server to query`
`    -h, --help: the HELP section`
`    -d, --debug: enable debugging`

Code: 

    zpl_opts opts = {{0}};

    zpl_opts_init(&opts, zpl_heap(), argv[0]);

    zpl_opts_add(&opts, "n", "hostname", "hostname to get DNS query for", ZPL_OPTS_STRING);
    zpl_opts_add(&opts, "s", "dns_server", "dns server to query", ZPL_OPTS_STRING);
    zpl_opts_add(&opts, "h", "help", "the HELP section", ZPL_OPTS_FLAG);
    zpl_opts_add(&opts, "d", "debug", "enable debugging", ZPL_OPTS_FLAG);
    zpl_opts_positional_add(&opts, "dns_server");
    zpl_opts_positional_add(&opts, "hostname");

    int32_t opts_compile = zpl_opts_compile(&opts, argc, argv);
    char *hostname;
    char *dns_server;

    if (opts_compile && zpl_opts_positionals_filled(&opts)) {
        // print help menu
        int32_t help = zpl_opts_has_arg(&opts, "help");
        if (help) {
            zpl_opts_print_help(&opts);
            return 0;
        }
        // enable debug mode
        debug = zpl_opts_has_arg(&opts, "debug");
        hostname = zpl_opts_string(&opts, "hostname", NULL);
        dns_server = zpl_opts_string(&opts, "dns_server", NULL);

    }
    else {
        zpl_opts_print_errors(&opts);
        zpl_opts_print_help(&opts);
        return 0;
    }

Maybe I'm doing something wrong or it just works like that, not sure

Thanks!

**Comment by inlife** [comment]
Thank you @robozman for the report!
We gonna look into the issue and get back to you soon.

**Comment by zaklaus** [comment]
Hey @robozman,

I see what the issue is, this is due to the fact I incorrectly handled flags which recognized positional values as its own. I will push the fix ASAP.

Thank you for using this library, feel free to report any more issues you encounter!

**Comment by zaklaus** [comment]
The fix is up as of ff6509ebf898abf289d50b1642587239b21d0aaa.

In case this issue was resolved, feel free to close it.

**Comment by robozman** [comment]
Just tested it and it seems to be now working as it should. Thanks for fixing this so quickly!


RE: ordering of positionals
I had noticed that behavior but I think I just assumed it worked as stack, hence the ordering you pointed out that I was using. Seems to be working as a FIFO now.

Makes more sense the updated way. First call to `zpl_opts_positional_add` corresponds to the left most positional, etc.


Thanks again and thanks for the library, it's very useful. Will definitely report any other issues I may encounter.
