### ISSUE TITLE
WIN32_LEAN_AND_MEAN macro redefinition warning

### ISSUE THREAD

**Issue by markatk** [zpl-c/zpl#24]
Because zpl defines as `#define WIN32_LEAN_AND_MEAN 1` instead of `#define WIN32_LEAN_AND_MEAN`. as I think is the usual way (see example link from msdn), I get a lot of `warning C4005: 'WIN32_LEAN_AND_MEAN': macro redefinition` because another library I use is also defining this "the normal way". By omitting the trailing 1 this could be fixed.

Example: https://docs.microsoft.com/de-de/previous-versions/technical-content/ms741665(v=vs.85)

**Comment by zaklaus** [comment]
Hello @markatk, thank you for reporting this issue. I will fix it right away, I appreciate the help.

**Comment by zaklaus** [comment]
Issue should be fixed by now.
