### ISSUE TITLE
Unsafe functions on windows

### ISSUE THREAD

**Issue by markatk** [zpl-c/zpl#25]
If you use zpl on windows (at least with MSVC) you get 2 unsafe code warnings because of `tmpfile` and `getenv` function calls. Maybe fix the warning with something like

```
#ifdef _WIN32
tmpfile_s(...);
#else
tmpfile(...);
#endif
```

Lines:
- zpl.h (9012)
- zpl.h (10272)

**Comment by zaklaus** [comment]
Thanks for the report, I'm on it.

**Comment by zaklaus** [comment]
Warnings are gone now. Thanks for the report again!
