### ISSUE TITLE
Comparisons against EOF fail when compiled with -funsigned-char

### ISSUE THREAD

**Issue by TerminX** [zpl-c/zpl#30]
See https://www.linuxtopia.org/online_books/an_introduction_to_gcc/gccintro_71.html

**Comment by zaklaus** [comment]
Thank you, I will definitely sit down to this and fix all the occurences, your help is very appreciated.

**Comment by zaklaus** [comment]
Fixed in https://github.com/zpl-c/zpl/commit/f577dedefa017030fb303494f96d6bd2b9f82aab
