### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by dangerousHobo** [zpl-c/zpl#34]
I'm trying to compile a simple example on Linux with gcc 7.4.0

I ran the `build.py` script and then ran `build_tests.sh.bat` and didn't get any errors.

Then I compile with the following:

```
gcc -g -Wall -Wextra -std=c11 -Izpl/code -o a.out test.c -pthread -lm -ldl
```

and get the following errors:

```
zpl/code/zpl.h: In function ‘zpl_vm_alloc’:
zpl/code/zpl.h:7450:23: error: ‘MAP_ANON’ undeclared (first use in this function); did you mean ‘FP_NAN’?
 #define MAP_ANONYMOUS MAP_ANON
                       ^

zpl/code/zpl.h:7480:41: error: ‘MADV_DONTNEED’ undeclared (first use in this function)
     int err = madvise(vm.data, vm.size, MADV_DONTNEED);
                                         ^~~~~~~~~~~~~

zpl/code/zpl.h: In function ‘zpl_fs_get_type’:
zpl/code/zpl.h:11157:25: error: ‘S_IFDIR’ undeclared (first use in this function); did you mean ‘S_ISDIR’?
         if( s.st_mode & S_IFDIR )
                         ^~~~~~~
                         S_ISDIR
```

test.c
```
#include  <stdio.h>
#define ZPL_IMPLEMENTATION
#include "zpl.h"

int main (int argc, char** argv)
{
	zpl_file_contents fc = zpl_file_read_contents(zpl_heap(), true, argv[1]);
	zpl_json_object root = {0};
	u8 err;

	zpl_json_parse(&root, fc.size, (char *)fc.data, zpl_heap(), true, &err);
	printf("%s\n %s\n", root.name, root.string);
	zpl_json_free(&root);
	zpl_file_free(&fc);

	return 0;
}
```

Not sure if there is an issue in `zpl` or if I'm doing something wrong.
Thanks!

**Comment by zaklaus** [comment]
Hi, which operating system are you trying to build it on?

**Comment by dangerousHobo** [comment]
Linux, Xubuntu 18.04.3 (x86_64)

**Comment by zaklaus** [comment]
I will try to reproduce this issue, thanks!

**Comment by zaklaus** [comment]
It seems like there was a change in the latest distro regarding some standard libraries. I can reproduce this issue when using `-std=c11` standard, but the code compiles under `-std=gnu11` fine.

Apart from that, you will get a linker error for `zpl_file_free` as such function doesn't exist.

I will experiment with the issue in question however, it seems like we're missing a `sys/mman.h` header include that contains those symbols.

**Comment by dangerousHobo** [comment]
Thanks @zaklaus, by using `-std=gnu11` and fixing the function name I was able to get the example compiling.

**Comment by zaklaus** [comment]
This issue will become fixed after the upcoming refactor. You can re-open it once the new update lands and the issue will persist, closing for now.
