### ISSUE TITLE
Cross Compile error on ARM

### ISSUE THREAD

**Issue by dangerousHobo** [zpl-c/zpl#35]
Hello, I've tried cross-compiling the example I'd shown in issue #34.
Cross compile toolchain and Linux OS is one built from Buildroot, with GCC version 6.4.0 (Target: arm-bulidroot-linux-gnueabihf, Arch: armv7 (32bit)).

The error:

```
zpl.h:553:35: fatal error: emmintrin.h: No such file or directory
```

zpl.h:

```
550 #if !defined(ZPL_NO_SIMD)
551     #if !defined(ZPL_SYSTEM_ANDROID) && !defined(ZPL_SYSTEM_IOS)
552         #if !defined(ZPL_SYSTEM_EMSCRIPTEN)
553             #include <emmintrin.h>
554         #elif defined(ZPL_CPU_X86) && !defined(ZPL_SYSTEM_EMSCRIPTEN)
555             #include <xmmintrin.h>
556         #else
557             #include <sched.h>
558         #endif
559     #endif
560 #endif
```

`sched.h` exist on this platform, so I modified the header to have it take this path in the above snippet. This caused new compile errors about `Unknown architecture`. The main README mentions ARM is supported.

**Comment by zaklaus** [comment]
Just a heads up, @inlife is looking into the issue right now. Could you provide us with the device this was intended to be compiled for? ARM support was roughly tested only under Android device, so it's possible we're missing something.

**Comment by dangerousHobo** [comment]
The device was a SolidRun Hummingboard2. This has an NXP i.MX6 MPU (armv7, 32bit). The MPU is quite popular and found in many embedded products.
https://www.solid-run.com/nxp-family/hummingboard/

**Comment by zaklaus** [comment]
Thank you, we will see what can be done to fix this issue and get back to you once we come up with a solution.

**Comment by inlife** [comment]
hey @dangerousHobo 
we are reworking the library right now, could you try compiling the latest version from releases
https://github.com/zpl-c/zpl/releases/latest

this version now allows us to enable and disable various parts of the library
I would recommend to try compiling with `#define ZPL_NANO`

And then if that works fine you can try compiling it by enabling modules one by one (or in similar fashion):

```c
#define ZPL_ENABLE_TIMER
#define ZPL_ENABLE_HASHING
#define ZPL_ENABLE_REGEX
#define ZPL_ENABLE_EVENT
#define ZPL_ENABLE_DLL
#define ZPL_ENABLE_OPTS
#define ZPL_ENABLE_PROCESS
#define ZPL_ENABLE_MATH
#define ZPL_ENABLE_JSON
#define ZPL_ENABLE_THREADING
#define ZPL_ENABLE_THREADPOOL
#define ZPL_ENABLE_COROUTINES
```

**Comment by zaklaus** [comment]
Closed for inactivity. Please, reopen if you face any further issues.
