### ISSUE TITLE
Regarding addition of extra matrix functions which are required for non opengl environments

### ISSUE THREAD

**Issue by msmshazan** [zpl-c/zpl#42]
How will the API change in order to add Left handed coordinate system based matrix manipulation functions and Perspective and orthographic functions which allow a NDC range of [0..1] (eg. Direct3d)?

**Comment by zaklaus** [comment]
Unfortunately the math library was made with OpenGL in mind at first. At the moment I don't have any  plans to support other coordinate systems.

**Comment by msmshazan** [comment]
I am willing to make a PR to add support for this but I was wondering if you had something specific in mind before I start working on a PR to avoid getting it rejected

**Comment by zaklaus** [comment]
I'd like to know what your suggestion would be in that case.

**Comment by zaklaus** [comment]
I think we could append the `_lh` postfix for left-handed methods.

**Comment by msmshazan** [comment]
Then what about functions which require different NDC ranges ( [-1...1] vs [0...1] ) like projection functions?

**Comment by zaklaus** [comment]
We can go with `_dx` extension for now.

**Comment by zaklaus** [comment]
Done as of #43
