### ISSUE TITLE
Time: questionable unconditional access of `PMCCNTR` under `__ARM_ARCH_7A__`

### ISSUE THREAD

**Issue by helixhorned** [zpl-c/zpl#45]
Hello!

I'm questioning the implementation of `zpl_rdtsc()` under `#elif defined(__ARM_ARCH_7A__)` in `time.c`.

Initial observations on a test program (compiled with no special flags) exercising a single call of that function (outputting its return value) on a Raspberry Pi 4 running Raspberry Pi OS (32-bit):

```
$ gcc -O0 -ggdb zpl_rdtsc_test.c -o ts_gcc
$ clang -O0 -ggdb zpl_rdtsc_test.c -o ts_clang
```

- GCC: compiles when the commit of [PR #44](https://github.com/zpl-c/zpl/pull/44) is applied, outputs 0
- Clang (as obtained from https://releases.llvm.org/download.html#10.0.1): compiles, aborts with "Illegal instruction"

The first thing to note is that GCC and Clang compile different `#if` blocks: `#elif (__ARM_ARCH >= 6)` for GCC and `#elif defined(__ARM_ARCH_7A__)` for Clang. \
This is easily explained by looking at the macros that each of them pre-defines:

```
$ clang  -dM -E - </dev/null | grep ARM
```

has

```
#define __ARM_ARCH 7
#define __ARM_ARCH_7A__ 1
```

while the same invocation with `gcc` shows that by default, GCC targets ARM architectures upwards of version 6 instead.

The more interesting issue is the `SIGILL`. My question: *what is the background for accessing `PMCCNTR` unconditionally under `__ARM_ARCH_7A__`?*

According to the "ARM Architecture Reference Manual Armv7-A and Armv7-R edition", section "C12.9 Performance Monitor registers" (page 2314) -- more specifically, table C12-11 on page 2319 -- accessing the Cycle Count Register is still only allowed if the `PMUSERENR.EN` bit is set to 1, which in turn can not be set from PL0 (unprivileged) modes.

And, as the initial output of 0 suggests and an additional check confirms, `PMUSERENR.EN` as visible from userspace is indeed set to 0 on my system, at least without additional measures taken.

Presumably, the code in question does have a background [1], but then the preprocessor condition needs to be refined IMO.

[1] such a specific variant of the ARM architecture allowing implementations to omit the access control?

**Comment by zaklaus** [comment]
Unfortunately, the ARM-related implementation of `zpl_rdtsc` is very flawed due to a lack of expertise in that particular architecture.  I agree a refinement should be made to improve and better handle special conditions.

**Comment by helixhorned** [comment]
To me, the ARMv6-upward implementation seems perfectly fine to use on ARMv7 as well, but I assume there was an intention behind the special case for `__ARM_ARCH_7A__`? (And I furthermore assume that all code present in the codebase was actually executed at least once and found working, so that there exists at least one system on which the code in question ran through.)

@inlife, you probably had something in mind when you wrote it in commit 2a6e301848?

**Comment by inlife** [comment]
Hey @helixhorned 

Unfortunately, I can't say I remember any details about this specific macro sequence. 

> but then the preprocessor condition needs to be refined IMO.

I fully support the refinement, I assume you already have a great suggestion in mind?

**Comment by helixhorned** [comment]
I don't have a great suggestion but a humble one which I thought you might not like: namely removing the code under `#elif defined(__ARM_ARCH_7A__)` altogether. Now up in PR #46.

Maybe in the future, the original intention becomes apparent again (for example, maybe there is a variant of the Arm architecture that simply doesn't have access checks and selecting that architecture was the intent?) and then the code in question can be brought back again. In my opinion that's better than aborting with `SIGILL`. You decide, of course :).

**Comment by inlife** [comment]
Ok, I think that sounds quite reasonable 👍
Thank you!

**Comment by zaklaus** [comment]
Changes are now present in version 10.8.6. Should we close this issue?

**Comment by helixhorned** [comment]
> Changes are now present in version 10.8.6. Should we close this issue?

Cool with me! :+1:

**Comment by zaklaus** [comment]
Thanks for the contribution, I really appreciate it!

**Comment by helixhorned** [comment]
You're welcome!

Just a follow-up: I saw commit e426c2ff12 which moved the status on the Raspberry Pi from '❔' to '✅'.

I did not mean to imply that I had exercised the functionality offered by ZPL in its
entirety. In fact, I did not get the tests to build. After all, there still seem to be a few
corners that are unimplemented on ARM:

```
$ make code/tests/tester
=> Building tester
In file included from code/zpl.h:717,
                 from code/tests/tester.c:2:
code/source/threading/atomic.c:344:6: error: #error TODO: Implement Atomics for this CPU
     #error TODO: Implement Atomics for this CPU
      ^~~~~
In file included from code/zpl.h:718,
                 from code/tests/tester.c:2:
code/source/threading/fence.c: In function ‘zpl_yield_thread’:
code/source/threading/fence.c:37:10: error: #error Unknown architecture
         #error Unknown architecture
          ^~~~~

 (^ Same for ‘zpl_mfence’, ‘zpl_sfence’ and ‘zpl_lfence’.)

code/source/threading/thread.c: In function ‘zpl_thread_current_id’:
code/source/threading/thread.c:111:10: error: #error Unsupported architecture for zpl_thread_current_id()
         #error Unsupported architecture for zpl_thread_current_id()
          ^~~~~
make: *** [Makefile:59: code/tests/tester] Error 1
```

**Comment by inlife** [comment]
Ah, I assumed the mentioned previously issue was the only thing that was supported on Raspberry Pi. And since it got resolved it seemed a good idea to mark it as is.

@helixhorned would you like to introduce the improvements to the Raspberry Pi side of things?
