### ISSUE TITLE
`zpl_jobs_process` is expensive

### ISSUE THREAD

**Issue by liigo** [zpl-c/zpl#58]
`zpl_jobs_process`, usually called in a loop, has at least two expensive operations:

- sort array by priority [jobs.c#L141](https://github.com/zpl-c/zpl/blob/e465889f06e532e83fb747e0ee30eaf566206e10/code/source/jobs.c#L141)
- remove array element at index 0 [jobs.c#L155](https://github.com/zpl-c/zpl/blob/e465889f06e532e83fb747e0ee30eaf566206e10/code/source/jobs.c#L155)

**Comment by zaklaus** [comment]
Thanks for the report, we will replace the underlying queue with a linked list, which should eliminate both issues at once.

**Comment by zaklaus** [comment]
Hi, status can now be tracked on: https://github.com/zpl-c/zpl/pull/60

**Comment by zaklaus** [comment]
A new version of zpl has been released that contains a rewritten jobs system, feel free to have a look: https://github.com/zpl-c/zpl/releases/tag/11.0.0

**Comment by zaklaus** [comment]
I am closing this issue for now, feel free to re-open if you wish to.
