### ISSUE TITLE
zpl_random_range_i64 generates value out of range

### ISSUE THREAD

**Issue by Bluelet** [zpl-c/zpl#83]
zpl_i64 zpl_random_range_i64(zpl_random *r, zpl_i64 lower_inc, zpl_i64 higher_inc) {
    zpl_u64 u = zpl_random_gen_u64(r);
    zpl_i64 i = *cast(zpl_i64 *)&u;
    zpl_i64 diff = higher_inc-lower_inc+1;
    i %= diff;
    i += lower_inc;
    return i;
}

if lower_inc is 0 and higher_inc is 1, the function generates '-1' as return value.

**Comment by zaklaus** [comment]
Thank you for your contribution!

This is fixed in https://github.com/zpl-c/zpl/commit/9cdd9ee33d20e6e682cd75f5d20490a1a60c4b51
