### ISSUE TITLE
Undecorated 'cast' macro in helpers.h

### ISSUE THREAD

**Issue by TheMartianObserver** [zpl-c/zpl#88]
ZPL includes a `cast` macro defined in helpers.h, which unfortunately can interact poorly with other code that uses `cast` in code. Any reason to not append a `zpl_` to that macro?

If there isn't a problem with that, I'll submit a PR.

Thanks!

**Comment by zaklaus** [comment]
Hi, it's an old leftover that needs updating, so I agree it should be prefixed. You can submit a PR if you want. 👍🏻
